.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-GERRIT" "1" "June 2015" "" ""
.
.SH "NAME"
\fBgit\-gerrit\fR \- a non\-interactive, command\-line gerrit interface
.
.SH "SYNOPSIS"
\fBgit gerrit\fR [branch:\fIproject branch\fR] [topic:\fIpatch topic\fR] [type:\fIreview|draft\fR]
.
.P
\fBgit gerrit\fR review [branch:\fIproject branch\fR] [topic:\fIpatch topic\fR] [type:\fIreview|draft\fR]
.
.P
\fBgit gerrit\fR push [branch:\fIproject branch\fR] [topic:\fIpatch topic\fR] [type:\fIreview|draft\fR]
.
.P
\fBgit gerrit\fR get \fIpatches\fR
.
.P
\fBgit gerrit\fR pull \fIpatches\fR
.
.P
\fBgit gerrit\fR \fI\-2|\-1|0|+1|+2\fR \fIpatches\fR
.
.P
\fBgit gerrit\fR retest \fIpatches\fR
.
.P
\fBgit gerrit\fR submit \fIpatches\fR
.
.P
\fBgit gerrit\fR ls [query]
.
.P
\fBgit gerrit\fR list [query]
.
.P
\fBgit gerrit\fR info \fIpatches\fR
.
.P
\fBgit gerrit\fR browse \fIpatches\fR
.
.P
\fBgit gerrit\fR query \fIquery\fR
.
.P
\fBgit gerrit\fR help
.
.P
\fBgit gerrit\fR version
.
.SH "DESCRIPTION"
A non\-interactive, command\-line interface to a Gerrit Code Review server\.
.
.P
\fBgit\-gerrit\fR aims to be an interface to Gerrit that does not impede your workflow, but instead acts as a way to compliment it, and integrate the normal workflow of using Git and writing code into the code review process\.
.
.P
Unlike the Gerrit web interface, it does not aim to be \fIthe\fR definitive way to access Gerrit and review code\. Instead, \fBgit\-gerrit\fR means to add features that are similar in functionality to Git\'s commands, and tries to share the same general feel\. It does not ask for unneeded input, and it does not provide comment viewing; the web is for reading, the command line is for getting your work done, and testing every last patch from the 3 page patch queue you\'ve been neglecting\.
.
.SH "FEATURES"
\fBgit\-gerrit\fR has a few main features: querying a Gerrit server, pulling patches from it, submitting patches for review, and applying Code\-Reviews to patches on Gerrit\.
.
.P
It also shares some compatibility with a program it aims to replace, git\-review(1), and can read it\'s \.gitreview configuration files usually located in the root of a Git repository\.
.
.P
In addition, \fBgit\-gerrit\fR has some other features, such as\.\.\.
.
.IP "\(bu" 4
Opening URLs of patches on the remote Gerrit server in your browser\.:
.
.IP "\(bu" 4
Running raw queries on the Gerrit server, returning formatted results\.:
.
.IP "\(bu" 4
Showing in\-depth information about certain patches, without needing to open a browser\.
.
.IP "" 0
.
.SH "COMMANDS"
If no command is given, \fBgit gerrit review\fR is the default action\.
.
.TP
\fBreview\fR [branch:\fIproject branch\fR] [topic:\fIpatch topic\fR] [type:\fIreview|draft\fR]
Sends all local commits to Gerrit for review\.
.
.IP
If you set \fBtype\fR to \fBdraft\fR, that will push patches as drafts, rather than world\-viewable patches\.
.
.IP
If no \fBbranch\fR is given, \fBbranch:<current branch>\fR is assumed\. If no \fBtype\fR is given, \fBtype:review\fR is assumed\.
.
.TP
\fBpush\fR
An alias for \fBreview\fR\.
.
.TP
\fBget\fR \fIpatches\fR
Fetches all patches given as arguments from Gerrit, and then applies them to your working copy of the tree\. Any conflicts will result the \fBgit am\fR session being halted, and \fBgit\-gerrit\fR will quit, printing the location of the failed patches\.
.
.TP
\fBpull\fR
An alias for \fBpull\fR\.
.
.TP
\fB\-2\fR, \fB\-1\fR, \fB0\fR, \fB+1\fR, \fB+2\fR \fIpatches\fR
Apply the corrisponding Code\-Review to each patch given\.
.
.TP
\fBsubmit\fR \fIpatches\fR
Submit each patch given to the upstream copy of the repository\.
.
.TP
\fBretest\fR \fIpatches\fR
Apply Retest+1 to each patch given\. This probably only does anything if you have Jenkins integrated with your Gerrit server\.
.
.TP
\fBlist\fR [query]
List reviews matching \fIquery\fR on the current project\. If no query is given, "status:open" is the default query\.
.
.TP
\fBbrowse\fR \fIpatches\fR
Opens the URL to each patch with $BROWSER\.
.
.IP
Fails if $BROWSER is not set\.
.
.TP
\fBquery\fR \fIquery\fR
Runs a raw query on Gerrit, and shows the results formatted\.
.
.TP
\fBhelp\fR
Shows a short help message\.
.
.TP
\fBversion\fR
Prints the current version and copyright information\.
.
.SH "CONFIGURATION"
\fBgit\-gerrit\fR does not have a large amount of configuration variables at the moment, other than configuring how it connects to Gerrit\.
.
.SS "Git configuration variables"
.
.TP
\fBgitreview\.username\fR
This sets the username which is used for connecting to Gerrit\. For example, if you have a Gerrit server which is located at \fBgerrit\.foobar\.biz\fR, and \fBgitreview\.username\fR is set to \fBMoo\fR, \fBgit\-gerrit\fR would connect to the SSH server that Gerrit runs with \fBMoo@gerrit\.foobar\.biz\fR\. If this is not set, SSH would connect with the username you are logged in as locally\.
.
.IP
ex\. \fBgitreview\.username = Moo\fR
.
.TP
\fBremote\.gerrit\.url\fR
This is where the Gerrit instance\'s SSH remote is set\. \fBgit\-gerrit\fR adds this by itself if it does not exist, using information from the \.gitreview file in the root of the Git repository\.
.
.IP
ex\. \fBremote\.gerrit\.url = ssh://Moo@gerrit\.foobar\.biz:29418/baz\.git\fR
.
.SS "\.gitreview variables"
.
.TP
\fBhost\fR
Required variable\. This is where the host that the Gerrit server is located should be entered\.
.
.IP
ex\. \fBhost=gerrit\.foobar\.biz\fR
.
.TP
\fBport\fR
Optional variable\. This is the port which the Gerrit server\'s SSH server is served on\. If it is not set, we assume \fB29418\fR, which is the default SSH port for a Gerrit server\.
.
.IP
ex\. \fBport=5000\fR, which would make \fBgit\-gerrit\fR connect to \fBssh://gerrit\.foobar\.biz:5000\fR\.
.
.TP
\fBproject\fR
Required variable\. This is the name of the repository on Gerrit\.
.
.IP
ex\. \fBproject=baz\fR, which would make \fBgit\-gerrit\fR push and pull patches from \fBssh://gerrit\.foobar\.biz:5000/baz\.git\fR\.
.
.SH "DIFFERENCES FROM GIT\-REVIEW(1)"
Unlike git\-review(1), \fBgit\-gerrit\fR does not prompt when you attempt to send multiple commits to Gerrit, which would create multiple patches\.
.
.P
It does not support all parameters that a \.gitreview file could contain,it only looks for the \fBhost\fR, \fBproject\fR, and \fBport\fR parameters\. Things such as your Gerrit username should be set in Git\'s configuration\.
.
.SH "COPYRIGHT"
Written by Kylie McClain \fIsomasis@exherbo\.org\fR
.
.P
\fIhttps://github\.com/Somasis/git\-gerrit\fR
.
.SH "LICENSE"
Licensed under the ISC license\.
.
.P
Copyright (c) 2015 Kylie McClain \fIsomasis@exherbo\.org\fR
.
.P
Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies\.
.
.P
THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE\.
.
.SH "SEE ALSO"
git\-review(1), git(1)
